name: Only on Dev Push & Main PR

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"
      - name: Build the Docker image for dev branch
        run: |
          timestamp=$(echo ${{ steps.timestamp.outputs.timestamp }})
          docker build -t custlynotts/simple-server:dev-${timestamp} .
  build-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"
      - name: Build the Docker image for main branch
        run: |
          timestamp=$(echo ${{ steps.timestamp.outputs.timestamp }})
          docker build -t custlynotts/simple-server:main-${timestamp} .


 push_to_registry:
  name: Push Docker image to Docker Hub
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: custlynotts/simple-server

    - name: Generate timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: custlynotts/simple-server:${{ github.ref }}-${{ steps.timestamp.outputs.timestamp}}
        labels: ${{ steps.meta.outputs.labels }}

